apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: demo
  namespace: participant
  annotations:
    # AWS Load Balancer Controller
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing

    # Ingress
    kubernetes.io/ingress.class: nginx

    # Cert Manager
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: nginx
  rules:
  - host: demo.k8s.aws-tests.skyworkz.nl
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: demo
            port:
              number: 8080
  tls:
  - hosts:
    - demo.k8s.aws-tests.skyworkz.nl