apiVersion: v2
name: argocd-init
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "1.16.0"

dependencies:
# https://github.com/argoproj/argo-helm/tree/main/charts/argo-cd
- name: argo-cd
  version: 5.51.0
  repository: https://argoproj.github.io/argo-helm
