argo-cd:
  fullnameOverride: argo

  server:
    ingress:
      enabled: true
      annotations:
        # Avoid ERR_TOO_MANY_REDIRECTS
        nginx.ingress.kubernetes.io/rewrite-target: /
      ingressClassName: nginx
      hosts:
        - argocd.k8s.aws-tests.skyworkz.nl
      tls:
        - hosts:
            - argocd.k8s.aws-tests.skyworkz.nl

  configs:
    params:
      server.insecure: true