argo-cd:
  fullnameOverride: argo

  server:
    ingress:
      enabled: true
      annotations:
        # Avoid ERR_TOO_MANY_REDIRECTS
        nginx.ingress.kubernetes.io/rewrite-target: /
        # add an annotation indicating the issuer to use.
        cert-manager.io/cluster-issuer: letsencrypt-prod
      ingressClassName: nginx
      hosts:
        - argocd.k8s.aws-tests.skyworkz.nl
      tls:
        - hosts:
            - argocd.k8s.aws-tests.skyworkz.nl
          secretName: argocd-tls

  configs:
    cm:
      #admin.enabled: false
      dex.config: |
        frontend:
          issuer: Skyworkz Training Platform
          logoURL: ./theme/skyworkz.png
          theme: dark
        connectors:
        - type: github
          id: github
          name: GitHub
          config:
            clientID: $github-client-secret:client-id
            clientSecret: $github-client-secret:client-secret
            orgs:
            - name: skyworkz
        staticClients:
        - id: oauth2-proxy
          redirectURIs:
          - 'https://oauth2.k8s.aws-tests.skyworkz.nl/oauth2/callback'
          name: 'oauth2-proxy'
          secret: eHnfU8jvesGiTUO4e4nZYGYGNXyXaDOsO2lcjDiT49M=
        enablePasswordDB: true
        staticPasswords:
        - email: "tom@skyworkz.cloud"
          username: "tom-cloud"
          hash: "$2a$10$2b2cU8CPhOTaGrs1HRQuAueS7JTT5ZHsHSzYiFPm1leZck7Mc8T4W"
          userID: "08a8684b-db88-4b73-90a9-3cd1661f5466"
        - email: "leo@skyworkz.cloud"
          username: "leo-cloud"
          hash: "$2a$10$2b2cU8CPhOTaGrs1HRQuAueS7JTT5ZHsHSzYiFPm1leZck7Mc8T4W"
          userID: "08a8684b-db88-4b73-90a9-3cd1661f5466"
        - email: "robert@skyworkz.cloud"
          username: "robert-cloud"
          hash: "$2a$10$2b2cU8CPhOTaGrs1HRQuAueS7JTT5ZHsHSzYiFPm1leZck7Mc8T4W"
          userID: "08a8684b-db88-4b73-90a9-3cd1661f5466"

      url: https://argocd.k8s.aws-tests.skyworkz.nl
    rbac:
      # -- The name of the default role which Argo CD will falls back to, when authorizing API requests (optional).
      # If omitted or empty, users may be still be able to login, but will see no apps, projects, etc...
      # Default: policy.default: ""
      policy.default: ''

      # Policy rules are in the form:
      #  p, subject, resource, action, object, effect
      # Role definitions and bindings are in the form:
      #  g, subject, inherited-subject
      # Default: policy.csv: ""
      policy.csv: |
        p, role:skyworkz-engineers-role, applications, create, */*, allow
        p, role:skyworkz-engineers-role, applications, delete, */*, allow
        p, role:skyworkz-engineers-role, applications, get, */*, allow
        p, role:skyworkz-engineers-role, applications, override, */*, allow
        p, role:skyworkz-engineers-role, applications, sync, */*, allow
        p, role:skyworkz-engineers-role, applications, update, */*, allow
        p, role:skyworkz-engineers-role, repositories, create, *, allow
        p, role:skyworkz-engineers-role, repositories, update, *, allow
        p, role:skyworkz-engineers-role, repositories, delete, *, allow
        g, skyworkz:Engineers, role:skyworkz-engineers-role
    params:
      server.insecure: true




