argo-cd:
  fullnameOverride: argo

  server:
    ingress:
      enabled: true
      annotations:
        # AWS Load Balancer Controller
        kubernetes.io/ingress.class: alb
        alb.ingress.kubernetes.io/scheme: internet-facing
        # Ingress
        kubernetes.io/ingress.class: nginx
        # Avoid ERR_TOO_MANY_REDIRECTS
        nginx.ingress.kubernetes.io/rewrite-target: /

        # external-dns specific configuration for creating route53 record-set
        external-dns.alpha.kubernetes.io/hostname: argocd.k8s.aws-tests.skyworkz.nl
      ingressClassName: nginx
      hosts:
        - argocd.k8s.aws-tests.skyworkz.nl
      tls:
        - hosts:
            - argocd.k8s.aws-tests.skyworkz.nl

  configs:
    params:
      server.insecure: true