apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: '{"apiVersion":"rbac.authorization.k8s.io/v1","kind":"ClusterRole","metadata":{"annotations":{},"name":"eks:k8s-metrics"},"rules":[{"apiGroups":[""],"resources":["endpoints","pods","nodes"],"verbs":["list"]},{"apiGroups":["apps"],"resources":["deployments"],"verbs":["list"]},{"nonResourceURLs":["/metrics","/metrics/slis","/debug/api_priority_and_fairness/*"],"verbs":["get"]}]}

      '
  name: eks:k8s-metrics
rules:
- apiGroups:
  - ''
  resources:
  - endpoints
  - pods
  - nodes
  verbs:
  - list
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - list
- nonResourceURLs:
  - /metrics
  - /metrics/slis
  - /debug/api_priority_and_fairness/*
  verbs:
  - get
