apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: '{"apiVersion":"rbac.authorization.k8s.io/v1","kind":"ClusterRole","metadata":{"annotations":{},"name":"eks:cluster-event-watcher"},"rules":[{"apiGroups":[""],"resources":["pods","nodes"],"verbs":["get","list","watch"]}]}

      '
  name: eks:cluster-event-watcher
rules:
- apiGroups:
  - ''
  resources:
  - pods
  - nodes
  verbs:
  - get
  - list
  - watch
