apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: '{"apiVersion":"rbac.authorization.k8s.io/v1","kind":"ClusterRole","metadata":{"annotations":{},"name":"eks:service-operations"},"rules":[{"nonResourceURLs":["/metrics","/debug/api_priority_and_fairness/*"],"verbs":["get"]},{"apiGroups":["metrics.k8s.io"],"resources":["pods","nodes"],"verbs":["get","list","watch"]},{"apiGroups":[""],"resources":["endpoints","persistentvolumeclaims","persistentvolumeclaims/status","pods","replicationcontrollers","replicationcontrollers/scale","serviceaccounts","services","services/status","bindings","events","limitranges","namespaces/status","pods/status","replicationcontrollers/status","resourcequotas","resourcequotas/status","namespaces","nodes","nodes/status"],"verbs":["get","list","watch"]},{"apiGroups":["discovery.k8s.io"],"resources":["*"],"verbs":["get","list","watch"]},{"apiGroups":["apps"],"resources":["*"],"verbs":["get","list","watch"]},{"apiGroups":["autoscaling"],"resources":["*"],"verbs":["get","list","watch"]},{"apiGroups":["batch"],"resources":["*"],"verbs":["get","list","watch"]},{"apiGroups":["extensions"],"resources":["*"],"verbs":["get","list","watch"]},{"apiGroups":["policy"],"resources":["*"],"verbs":["get","list","watch"]},{"apiGroups":["networking.k8s.io"],"resources":["*"],"verbs":["get","list","watch"]},{"apiGroups":["coordination.k8s.io"],"resources":["*"],"verbs":["get","list","watch"]},{"apiGroups":["rbac.authorization.k8s.io"],"resources":["*"],"verbs":["get","list","watch"]},{"apiGroups":["storage.k8s.io"],"resources":["*"],"verbs":["get","list","watch"]},{"apiGroups":["certificates.k8s.io"],"resources":["*"],"verbs":["get","list","watch"]},{"apiGroups":["admissionregistration.k8s.io"],"resources":["*"],"verbs":["get","list","watch"]},{"apiGroups":["apiextensions.k8s.io"],"resources":["*"],"verbs":["get","list","watch"]},{"apiGroups":["apiregistration.k8s.io"],"resources":["*"],"verbs":["get","list","watch"]},{"apiGroups":["policy"],"resources":["podsecuritypolicies"],"verbs":["get","list","watch"]},{"apiGroups":["node.k8s.io"],"resources":["*"],"verbs":["get","list","watch"]},{"apiGroups":["flowcontrol.apiserver.k8s.io"],"resources":["*"],"verbs":["get","list","watch"]},{"apiGroups":["scheduling.k8s.io"],"resources":["*"],"verbs":["get","list"]},{"apiGroups":["crd.k8s.amazonaws.com"],"resources":["eniconfigs"],"verbs":["get","list","watch"]},{"apiGroups":["vpcresources.k8s.aws"],"resources":["securitygrouppolicies"],"verbs":["get","list","watch"]}]}

      '
  name: eks:service-operations
rules:
- nonResourceURLs:
  - /metrics
  - /debug/api_priority_and_fairness/*
  verbs:
  - get
- apiGroups:
  - metrics.k8s.io
  resources:
  - pods
  - nodes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ''
  resources:
  - endpoints
  - persistentvolumeclaims
  - persistentvolumeclaims/status
  - pods
  - replicationcontrollers
  - replicationcontrollers/scale
  - serviceaccounts
  - services
  - services/status
  - bindings
  - events
  - limitranges
  - namespaces/status
  - pods/status
  - replicationcontrollers/status
  - resourcequotas
  - resourcequotas/status
  - namespaces
  - nodes
  - nodes/status
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - discovery.k8s.io
  resources:
  - '*'
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - '*'
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - autoscaling
  resources:
  - '*'
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - batch
  resources:
  - '*'
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - extensions
  resources:
  - '*'
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - policy
  resources:
  - '*'
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - networking.k8s.io
  resources:
  - '*'
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - coordination.k8s.io
  resources:
  - '*'
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - '*'
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - storage.k8s.io
  resources:
  - '*'
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - certificates.k8s.io
  resources:
  - '*'
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - '*'
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - '*'
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apiregistration.k8s.io
  resources:
  - '*'
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - policy
  resources:
  - podsecuritypolicies
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - node.k8s.io
  resources:
  - '*'
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - flowcontrol.apiserver.k8s.io
  resources:
  - '*'
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - scheduling.k8s.io
  resources:
  - '*'
  verbs:
  - get
  - list
- apiGroups:
  - crd.k8s.amazonaws.com
  resources:
  - eniconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - vpcresources.k8s.aws
  resources:
  - securitygrouppolicies
  verbs:
  - get
  - list
  - watch
