apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: '{"apiVersion":"rbac.authorization.k8s.io/v1","kind":"ClusterRole","metadata":{"annotations":{},"name":"eks:tagging-controller"},"rules":[{"apiGroups":[""],"resources":["nodes"],"verbs":["get","patch"]}]}

      '
  name: eks:tagging-controller
rules:
- apiGroups:
  - ''
  resources:
  - nodes
  verbs:
  - get
  - patch
