apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: '{"apiVersion":"rbac.authorization.k8s.io/v1","kind":"ClusterRole","metadata":{"annotations":{},"name":"eks:cloudwatch-agent-role"},"rules":[{"apiGroups":[""],"resources":["pods","nodes","endpoints"],"verbs":["list","watch"]},{"apiGroups":["apps"],"resources":["replicasets"],"verbs":["list","watch"]},{"apiGroups":["batch"],"resources":["jobs"],"verbs":["list","watch"]},{"apiGroups":[""],"resources":["nodes/proxy"],"verbs":["get"]},{"apiGroups":[""],"resources":["nodes/stats","events"],"verbs":["create"]}]}

      '
  name: eks:cloudwatch-agent-role
rules:
- apiGroups:
  - ''
  resources:
  - pods
  - nodes
  - endpoints
  verbs:
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - replicasets
  verbs:
  - list
  - watch
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - list
  - watch
- apiGroups:
  - ''
  resources:
  - nodes/proxy
  verbs:
  - get
- apiGroups:
  - ''
  resources:
  - nodes/stats
  - events
  verbs:
  - create
