apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: '{"apiVersion":"rbac.authorization.k8s.io/v1","kind":"ClusterRole","metadata":{"annotations":{},"name":"eks:fargate-scheduler"},"rules":[{"apiGroups":[""],"resources":["pods","persistentvolumes","persistentvolumeclaims"],"verbs":["get","list","watch"]},{"apiGroups":[""],"resources":["pods/status"],"verbs":["get","list","watch","update"]},{"apiGroups":[""],"resources":["configmaps"],"verbs":["get","list","watch","create"]},{"apiGroups":[""],"resourceNames":["fargate-scheduler"],"resources":["configmaps"],"verbs":["update"]},{"apiGroups":["coordination.k8s.io"],"resourceNames":["fargate-scheduler"],"resources":["leases"],"verbs":["get","update"]},{"apiGroups":["coordination.k8s.io"],"resources":["leases"],"verbs":["create"]},{"apiGroups":[""],"resources":["pods/binding"],"verbs":["create"]},{"apiGroups":[""],"resources":["nodes"],"verbs":["get","list","watch","delete"]},{"apiGroups":["events.k8s.io",""],"resources":["events"],"verbs":["create"]}]}

      '
  name: eks:fargate-scheduler
rules:
- apiGroups:
  - ''
  resources:
  - pods
  - persistentvolumes
  - persistentvolumeclaims
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ''
  resources:
  - pods/status
  verbs:
  - get
  - list
  - watch
  - update
- apiGroups:
  - ''
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
  - create
- apiGroups:
  - ''
  resourceNames:
  - fargate-scheduler
  resources:
  - configmaps
  verbs:
  - update
- apiGroups:
  - coordination.k8s.io
  resourceNames:
  - fargate-scheduler
  resources:
  - leases
  verbs:
  - get
  - update
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - create
- apiGroups:
  - ''
  resources:
  - pods/binding
  verbs:
  - create
- apiGroups:
  - ''
  resources:
  - nodes
  verbs:
  - get
  - list
  - watch
  - delete
- apiGroups:
  - events.k8s.io
  - ''
  resources:
  - events
  verbs:
  - create
