apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: '{"apiVersion":"rbac.authorization.k8s.io/v1","kind":"ClusterRole","metadata":{"annotations":{},"name":"eks:az-poller"},"rules":[{"apiGroups":[""],"resourceNames":["kubernetes"],"resources":["endpoints"],"verbs":["get","update"]}]}

      '
  name: eks:az-poller
rules:
- apiGroups:
  - ''
  resourceNames:
  - kubernetes
  resources:
  - endpoints
  verbs:
  - get
  - update
