apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: '{"apiVersion":"rbac.authorization.k8s.io/v1","kind":"ClusterRole","metadata":{"annotations":{},"name":"eks:certificate-controller-approver"},"rules":[{"apiGroups":["certificates.k8s.io"],"resourceNames":["kubernetes.io/kubelet-serving"],"resources":["signers"],"verbs":["approve"]}]}

      '
  name: eks:certificate-controller-approver
rules:
- apiGroups:
  - certificates.k8s.io
  resourceNames:
  - kubernetes.io/kubelet-serving
  resources:
  - signers
  verbs:
  - approve
