apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: sealed-secrets-web
  namespace: kube-system
spec:
  repo: https://ricoberger.github.io/helm-charts
  chart: sealed-secrets-web
  version: 2.4.0
  targetNamespace: sealed-secrets-web
  valuesContent: |-
    image:
      args:
      - --format
      - yaml
