apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: '{"apiVersion":"rbac.authorization.k8s.io/v1","kind":"Role","metadata":{"annotations":{},"name":"eks:certificate-controller","namespace":"kube-system"},"rules":[{"apiGroups":[""],"resources":["configmaps"],"verbs":["get","update","create"]},{"apiGroups":["coordination.k8s.io"],"resources":["leases"],"verbs":["create"]},{"apiGroups":["coordination.k8s.io"],"resourceNames":["eks-certificates-controller"],"resources":["leases"],"verbs":["get","update"]}]}

      '
  name: eks:certificate-controller
  namespace: kube-system
rules:
- apiGroups:
  - ''
  resources:
  - configmaps
  verbs:
  - get
  - update
  - create
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - create
- apiGroups:
  - coordination.k8s.io
  resourceNames:
  - eks-certificates-controller
  resources:
  - leases
  verbs:
  - get
  - update
