apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: '{"apiVersion":"rbac.authorization.k8s.io/v1","kind":"Role","metadata":{"annotations":{},"name":"eks:k8s-metrics","namespace":"kube-system"},"rules":[{"apiGroups":["apps"],"resourceNames":["aws-node"],"resources":["daemonsets"],"verbs":["get"]},{"apiGroups":["apps"],"resourceNames":["vpc-resource-controller"],"resources":["deployments"],"verbs":["get"]},{"apiGroups":[""],"resourceNames":["amazon-vpc-cni"],"resources":["configmaps"],"verbs":["list"]}]}

      '
  name: eks:k8s-metrics
  namespace: kube-system
rules:
- apiGroups:
  - apps
  resourceNames:
  - aws-node
  resources:
  - daemonsets
  verbs:
  - get
- apiGroups:
  - apps
  resourceNames:
  - vpc-resource-controller
  resources:
  - deployments
  verbs:
  - get
- apiGroups:
  - ''
  resourceNames:
  - amazon-vpc-cni
  resources:
  - configmaps
  verbs:
  - list
