apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: '{"apiVersion":"rbac.authorization.k8s.io/v1","kind":"Role","metadata":{"annotations":{},"name":"eks:addon-manager","namespace":"kube-system"},"rules":[{"apiGroups":["policy"],"resourceNames":["ebs-csi-controller-pod-disruption-budget","ebs-csi-controller"],"resources":["poddisruptionbudgets"],"verbs":["create","delete","get","list","patch","update","watch"]},{"apiGroups":[""],"resourceNames":["coredns","kube-proxy","kube-proxy-config"],"resources":["configmaps"],"verbs":["create","delete","get","list","patch","update","watch"]},{"apiGroups":["apps"],"resourceNames":["aws-node","kube-proxy","ebs-csi-node","ebs-csi-node-windows"],"resources":["daemonsets"],"verbs":["create","delete","get","list","patch","update","watch"]},{"apiGroups":["apps"],"resourceNames":["coredns","ebs-csi-controller"],"resources":["deployments"],"verbs":["create","delete","get","list","patch","update","watch"]},{"apiGroups":[""],"resourceNames":["kube-dns"],"resources":["services"],"verbs":["create","delete","get","list","patch","update","watch"]},{"apiGroups":[""],"resourceNames":["coredns","aws-node","kube-proxy","ebs-csi-controller-sa","ebs-csi-node-sa"],"resources":["serviceaccounts"],"verbs":["create","delete","get","list","patch","update","watch"]}]}

      '
  name: eks:addon-manager
  namespace: kube-system
rules:
- apiGroups:
  - policy
  resourceNames:
  - ebs-csi-controller-pod-disruption-budget
  - ebs-csi-controller
  resources:
  - poddisruptionbudgets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ''
  resourceNames:
  - coredns
  - kube-proxy
  - kube-proxy-config
  resources:
  - configmaps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resourceNames:
  - aws-node
  - kube-proxy
  - ebs-csi-node
  - ebs-csi-node-windows
  resources:
  - daemonsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resourceNames:
  - coredns
  - ebs-csi-controller
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ''
  resourceNames:
  - kube-dns
  resources:
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ''
  resourceNames:
  - coredns
  - aws-node
  - kube-proxy
  - ebs-csi-controller-sa
  - ebs-csi-node-sa
  resources:
  - serviceaccounts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
