apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: '{"apiVersion":"rbac.authorization.k8s.io/v1","kind":"Role","metadata":{"annotations":{},"name":"eks:authenticator","namespace":"kube-system"},"rules":[{"apiGroups":[""],"resources":["events"],"verbs":["create","update","patch"]},{"apiGroups":[""],"resourceNames":["aws-auth"],"resources":["configmaps"],"verbs":["get","list","watch"]}]}

      '
  name: eks:authenticator
  namespace: kube-system
rules:
- apiGroups:
  - ''
  resources:
  - events
  verbs:
  - create
  - update
  - patch
- apiGroups:
  - ''
  resourceNames:
  - aws-auth
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
