apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: '{"apiVersion":"rbac.authorization.k8s.io/v1","kind":"Role","metadata":{"annotations":{},"name":"eks-vpc-resource-controller-role","namespace":"kube-system"},"rules":[{"apiGroups":["apps"],"resourceNames":["vpc-resource-controller"],"resources":["deployments"],"verbs":["get","list","watch"]},{"apiGroups":[""],"resourceNames":["amazon-vpc-cni"],"resources":["configmaps"],"verbs":["get","list","watch"]},{"apiGroups":[""],"resources":["configmaps"],"verbs":["create","list","watch"]},{"apiGroups":[""],"resourceNames":["cp-vpc-resource-controller"],"resources":["configmaps"],"verbs":["get","update","patch"]},{"apiGroups":[""],"resources":["events"],"verbs":["create"]},{"apiGroups":["coordination.k8s.io"],"resources":["leases"],"verbs":["create"]},{"apiGroups":["coordination.k8s.io"],"resourceNames":["cp-vpc-resource-controller"],"resources":["leases"],"verbs":["get","update"]}]}

      '
  name: eks-vpc-resource-controller-role
  namespace: kube-system
rules:
- apiGroups:
  - apps
  resourceNames:
  - vpc-resource-controller
  resources:
  - deployments
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ''
  resourceNames:
  - amazon-vpc-cni
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ''
  resources:
  - configmaps
  verbs:
  - create
  - list
  - watch
- apiGroups:
  - ''
  resourceNames:
  - cp-vpc-resource-controller
  resources:
  - configmaps
  verbs:
  - get
  - update
  - patch
- apiGroups:
  - ''
  resources:
  - events
  verbs:
  - create
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - create
- apiGroups:
  - coordination.k8s.io
  resourceNames:
  - cp-vpc-resource-controller
  resources:
  - leases
  verbs:
  - get
  - update
