apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: '{"apiVersion":"rbac.authorization.k8s.io/v1","kind":"Role","metadata":{"annotations":{},"name":"eks:az-poller","namespace":"kube-system"},"rules":[{"apiGroups":["coordination.k8s.io"],"resourceNames":["kube-controller-manager","kube-scheduler","cloud-controller-manager","eks-certificates-controller","fargate-scheduler","cp-vpc-resource-controller","amazon-network-policy-controller-k8s"],"resources":["leases"],"verbs":["get","update"]}]}

      '
  name: eks:az-poller
  namespace: kube-system
rules:
- apiGroups:
  - coordination.k8s.io
  resourceNames:
  - kube-controller-manager
  - kube-scheduler
  - cloud-controller-manager
  - eks-certificates-controller
  - fargate-scheduler
  - cp-vpc-resource-controller
  - amazon-network-policy-controller-k8s
  resources:
  - leases
  verbs:
  - get
  - update
