apiVersion: v1
kind: Namespace
metadata:
  name: oauth2-proxy
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: oauth2-proxy
  namespace: kube-system
spec:
  repo: https://charts.bitnami.com/bitnami
  chart: oauth2-proxy
  version: 2.1.5
  targetNamespace: oauth2-proxy
  valuesContent: |-
    configuration:
      existingSecret: oauth2-proxy-secret
    extraArgs:
      - --provider=oidc
      - --oidc-issuer-url=http://argocd-server.argocd.svc.cluster.local/api/dex
      - --ssl-insecure-skip-verify=true
      - --insecure-oidc-skip-issuer-verification=true


