apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
- ../../base
- ingress.yaml
- secret-sso-bitbucket.yaml
- secret-sso-github.yaml
- secret-sso-argo-workflows.yaml

patchesStrategicMerge:
- argocd-cm.yaml
- argocd-rbac-cm.yaml
