oauth2-proxy:
  configuration:
    existingSecret: oauth2-proxy-secret
  nodeSelector:
    kubernetes.io/os: linux
    eks.amazonaws.com/capacityType: ON_DEMAND
  replicaCount: 2
  extraArgs:
    - --provider=oidc
    - --upstream=file:///dev/null
    - --upstream=http://oauth2-proxy-redirector/redirect/
    - --cookie-domain=.k8s.aws-tests.skyworkz.nl
    - --oidc-issuer-url=https://argocd.k8s.aws-tests.skyworkz.nl/api/dex
    - --scope=openid profile email groups
    - --whitelist-domain=.k8s.aws-tests.skyworkz.nl
    - --redirect-url=https://oauth2.k8s.aws-tests.skyworkz.nl/oauth2/callback
    - --set-authorization-header=true
    - --https-address=:4180
  redis:
    auth:
      existingSecret: redis-secret
