apiVersion: v1
kind: ConfigMap
metadata:
  name: oauth2-proxy-redirector
  namespace: kube-system
data:
  nginx.conf: |
    worker_processes 5;
    events {
    }
    http {
      server {
        listen 80 default_server;

        # error_log stderr;
        # access_log stderr;

        location = /healthcheck {
          add_header Content-Type text/plain;
          return 200 'ok';
        }
        location ~ /redirect/(.*) {
          return 307 https://$1$is_args$args;
        }
      }
    }