apiVersion: v1
kind: Secret
metadata:
  name: oauth2-proxy-secret
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app.kubernetes.io/part-of: argocd
type: Opaque
data:
  client-id: oauth2-proxy
  client-secret: eHnfU8jvesGiTUO4e4nZYGYGNXyXaDOsO2lcjDiT49M=
  cookie-secret: dWZ6eDcwZkV6ZVRZbUREbHlQUUFwbE9yVVBydDdnS1BjX3Z5R2hpUXlrMD0=
