apiVersion: v1
kind: Secret
metadata:
  name: oauth2-proxy-secret
  namespace: {{ .Release.Namespace | quote }}
type: Opaque
data:
  client-id: b2F1dGgyLXByb3h5
  client-secret: ZUhuZlU4anZlc0dpVFVPNGU0blpZR1lHTlh5WGFET3NPMmxjakRpVDQ5TT0=
  cookie-secret: dWZ6eDcwZkV6ZVRZbUREbHlQUUFwbE9yVVBydDdnS1BjX3Z5R2hpUXlrMD0=
