apiVersion: v1
kind: Secret
metadata:
  name: redis-secret
  namespace: {{ .Release.Namespace | quote }}
type: Opaque
data:
  redis-password: N0NWcGc4VVNmVWpfVkpEUG9rVE5PcmZLNTBOMnBxYjZDSFVtSXFZMW8wOD0K


