apiVersion: v1
kind: Service
metadata:
  name: oauth2-proxy-redirector
  namespace: kube-system
  labels:
    k8s-app: oauth2-proxy-redirector
spec:
  ports:
  - name: http
    protocol: TCP
    targetPort: http
    port: 80
  selector:
    k8s-app: oauth2-proxy-redirector