apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: maurice
namePrefix: maurice-

resources:
  - ../aws

patches:
  - target:
      kind: Ingress
      name: kubetrain
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value:  maurice.k8s.aws-tests.skyworkz.nl
      - op: replace
        path: /spec/tls/0/hosts/0
        value:  maurice.k8s.aws-tests.skyworkz.nl
      - op: replace
        path: /spec/tls/0/secretName
        value:  maurice-tls
  - target:
      kind: Ingress
      name: kubetrain-oauth2-proxy
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value:  maurice.k8s.aws-tests.skyworkz.nl
      - op: replace
        path: /spec/tls/0/hosts/0
        value:  maurice.k8s.aws-tests.skyworkz.nl
