apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: argocd-rbac-cm
    app.kubernetes.io/part-of: argocd
  name: argocd-rbac-cm
data:
  scopes: "[email,groups]"
  policy.default: role:none
  policy.csv: |
    g, johndoe, role:admin
    g, bennycornelissen-skyworkz, role:admin

