apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
  name: argocd-cm
data:
  url: https://argocd.k3d.localhost

  # local users
  accounts.johndoe: login

  dex.config: |
    connectors:
    - type: bitbucket-cloud
      # Required field for connector id.
      id: bitbucket-cloud
      # Required field for connector name.
      name: Bitbucket Cloud
      config:
        # Get field 'clientID' from K8s Secret 'argocd-dex-sso-secret'
        # See https://argo-cd.readthedocs.io/en/stable/operator-manual/user-management/#sensitive-data-and-sso-client-secrets
        clientID: $argocd-dex-sso-secret:clientID
        clientSecret: $argocd-dex-sso-secret:clientSecret
        redirectURI: http://127.0.0.1:5556/dex/callback
        # Optional teams whitelist, communicated through the "groups" scope.
        # If `teams` is omitted, all of the user's Bitbucket teams are returned when the groups scope is present.
        # If `teams` is provided, this acts as a whitelist - only the user's Bitbucket teams that are in the configured `teams` below will go into the groups claim.  Conversely, if the user is not in any of the configured `teams`, the user will not be authenticated.
        teams:
        - bennycornelissen-skyworkz
        # Optional parameter to include team groups.
        # If enabled, the groups claim of dex id_token will looks like this:
        # ["my_team", "my_team/administrators", "my_team/members"]
        #includeTeamGroups: true

