apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aws-load-balancer-controller
  namespace: kube-system
spec:
  project: default
  source:
    repoURL: https://github.com/skyworkz/kubernetes-training-setup-aws.git
    targetRevision: main
    path: kubernetes/cluster-services/aws-load-balancer-controller
  destination:
    server: "https://kubernetes.default.svc"
    namespace: kube-system
  syncPolicy:
    automated:
      selfHeal: true
      prune: true