apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../base
- ingress.yaml

patchesStrategicMerge:
- theia-deployment.yaml

patches:
- target:
    kind: StatefulSet
    labelSelector: "app=kubetrain"
  patch: |-
    - op: add
      path: /spec/template/spec/nodeSelector/eks.amazonaws.com~1capacityType
      value: ON_DEMAND
