# apiVersion: kustomize.config.k8s.io/v1beta1
# kind: Kustomization

# resources:
# - ../base
# - ingress.yaml

# patchesStrategicMerge:
# - vscode-deployment.yaml

# patches:
# - target:
#     kind: StatefulSet
#     labelSelector: "app=kubetrain"
#   patch: |-
#     - op: add
#       path: /spec/template/spec/nodeSelector/eks.amazonaws.com~1capacityType
#       value: ON_DEMAND


apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../base
- ingress.yaml

patches:
- path: vscode-deployment.yaml
  target:
    group: apps
    version: v1
    kind: Deployment
    name: vscode # Assuming the deployment name is vscode, specify the exact name
- target:
    group: apps
    version: v1
    kind: StatefulSet
    labelSelector: "app=kubetrain"
  patch: |-
    - op: add
      path: /spec/template/spec/nodeSelector/eks.amazonaws.com~1capacityType
      value: ON_DEMAND
