apiVersion: v2
name: ingress-nginx
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "1.16.0"

dependencies:
# https://artifacthub.io/packages/helm/ingress-nginx/ingress-nginx
- name: ingress-nginx
  version: 4.8.3
  repository: https://kubernetes.github.io/ingress-nginx