ingress-nginx:
  fullnameOverride: ingress-nginx
  namespace: ingress-nginx

  controller:
    replicaCount: 1
    ingressClassResource:
      default: true
    publishService:
      enabled: true
    nodeSelector:
      eks.amazonaws.com/capacityType: ON_DEMAND
    service:
      externalTrafficPolicy: "Local"
      annotations:
        service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp
        service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: '60'
        service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: 'true'
        service.beta.kubernetes.io/aws-load-balancer-type: nlb
    extraArgs:
      default-ssl-certificate: cert-manager/nginx-default-cert