ingress-nginx:
  fullnameOverride: ingress-nginx
  namespace: ingress-nginx

  controller:
    replicaCount: 1
    ingressClassResource:
      default: true
    publishService:
      enabled: true
    nodeSelector:
      eks.amazonaws.com/capacityType: ON_DEMAND
    service:
      externalTrafficPolicy: "Local"
      annotations:
        service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp
        service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: '60'
        service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: 'true'
        service.beta.kubernetes.io/aws-load-balancer-type: nlb
    extraArgs:
      default-ssl-certificate: cert-manager/nginx-default-cert

    config:
      custom-http-errors: "403,404,503"
    defaultBackend:
      enabled: true
      image:
        registry: registry.k8s.io
        image: ingress-nginx/nginx-errors
        tag: "v20230505@sha256:3600dcd1bbd0d05959bb01af4b272714e94d22d24a64e91838e7183c80e53f7f"
      extraVolumes:
      - name: custom-error-pages
        configMap:
          name: custom-error-pages
          items:
          - key: "403"
            path: "403.html"
          - key: "404"
            path: "404.html"
          - key: "503"
            path: "503.html"
      extraVolumeMounts:
      - name: custom-error-pages
        mountPath: /www