---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kubetrain
spec:
  rules:
  - host: kubedev.k3d.localhost
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: kubetrain
            port:
              number: 3000
