apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: demo2
  namespace: demo
spec:
  ingressClassName: nginx
  rules:
  - host: demo2.k8s.aws-tests.skyworkz.nl
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: demo
            port:
              number: 8080
  tls:
  - hosts:
    - demo2.k8s.aws-tests.skyworkz.nl