apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: kube-system
spec:
  project: default
  source:
    repoURL: https://github.com/skyworkz/kubernetes-training-setup-aws.git
    targetRevision: main
    path: kubernetes/cluster-services/ingress-nginx
  destination:
    server: "https://kubernetes.default.svc"
    namespace: ingress-nginx
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - CreateNamespace=true