apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: participant-john-doe
  namespace: kube-system
spec:
  project: default
  source:
    repoURL: https://github.com/skyworkz/kubernetes-training-setup-aws.git
    targetRevision: main
    path: kubernetes/participant
    helm:
      values: |
        participant.name: john-doe
  destination:
    server: "https://kubernetes.default.svc"
    namespace: participant-john-doe
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true