apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: participants
  namespace: kube-system
spec:
  generators:
  - list:
      elements:
      - namespace: tom
        name: tom
        email: tom@skyworkz.cloud
      #- namespace: leonardo
      #  participant:
      #    name: leonardo
      #    email: leonardo@skyworkz.cloud
      #- namespace: robert
      #  participant:
      #    name: robert
      #    email: robert@skyworkz.cloud
  template:
    metadata:
      name: participant-{{"{{"}}name{{"}}"}}
      namespace: kube-system
    spec:
      project: default
      source:
        repoURL: https://github.com/skyworkz/kubernetes-training-setup-aws.git
        targetRevision: main
        path: kubernetes/participant
        helm:
          values: |
            namespace: {{"{{"}}namespace{{"}}"}}
            participant.name: {{"{{"}}name{{"}}"}}
            participant.email: {{"{{"}}email{{"}}"}}
            trainers:
            {{- range .Values.trainers }}
            - {{.}}
            {{- end }}
      destination:
        server: "https://kubernetes.default.svc"
        namespace: kube-system
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
