apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: participants
  namespace: kube-system
spec:
  generators:
  - list:
      # Looping here over the name and emails of the participants
      elements:
      # - name: tom
      #   email: tom@skyworkz.cloud
      # - name: robert
      #   email: robert@skyworkz.cloud
      # - name: leonardo
      #   email: leonardo@skyworkz.cloud
      - name: maarten
        email: maarten@skyworkz.cloud
  template:
    metadata:
      name: participant-{{"{{"}}name{{"}}"}}
      namespace: kube-system
    spec:
      project: default
      source:
        repoURL: https://github.com/skyworkz/kubernetes-training-setup-aws.git
        targetRevision: main
        path: kubernetes/participant
        helm:
          values: |
            participant:
              name: {{"{{"}}name{{"}}"}}
              email: {{"{{"}}email{{"}}"}}
            trainers:
            {{- range .Values.trainers }}
            - {{.}}
            {{- end }}
      destination:
        server: "https://kubernetes.default.svc"
        namespace: kube-system
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
