apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

images:
- name: ghcr.io/dexidp/dex
  # Fixes issue with Bitbucket Cloud API deprecation for SSO
  # https://github.com/dexidp/dex/issues/2391
  newTag: v2.30.3

resources:
- namespace.yaml
- https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
