apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: '{"apiVersion":"rbac.authorization.k8s.io/v1","kind":"ClusterRoleBinding","metadata":{"annotations":{},"name":"vpc-resource-controller-rolebinding"},"roleRef":{"apiGroup":"rbac.authorization.k8s.io","kind":"ClusterRole","name":"vpc-resource-controller-role"},"subjects":[{"apiGroup":"rbac.authorization.k8s.io","kind":"User","name":"eks:vpc-resource-controller"},{"kind":"ServiceAccount","name":"eks-vpc-resource-controller","namespace":"kube-system"}]}

      '
  name: vpc-resource-controller-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: vpc-resource-controller-role
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: eks:vpc-resource-controller
- kind: ServiceAccount
  name: eks-vpc-resource-controller
  namespace: kube-system
