cluster-autoscaler:
  fullnameOverride: cluster-autoscaler
  namespace: kube-system

  autoDiscovery:
    clusterName: skyworkz-k8s-training-XHrFnl5s
  awsRegion: eu-west-1
  deployment:
    annotations:
      eks.amazonaws.com/role-arn: arn:aws:iam::267074127319:role/cluster-autoscaler-role
  rbac:
    serviceAccount:
      annotations:
        eks.amazonaws.com/role-arn: arn:aws:iam::267074127319:role/cluster-autoscaler-role
