---
apiVersion: v1
kind: Secret
metadata:
  name: kubetrain-workspace
stringData:
  git_url: git@github.com:some-repo/here.git
  git_ssh_key: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    some private key here
    -----END OPENSSH PRIVATE KEY-----



