apiVersion: v1
kind: ConfigMap
metadata:
  name: participant-git-config
  namespace: participant-{{ .Values.participant.name }}
data:
  .gitconfig: |
    [user]
    name = '{{ .Values.participant.name }}'
    email = "test@foo.com"
