apiVersion: v1
kind: ConfigMap
metadata:
  name: participant-git-config
  namespace: {{ .Values.namespace }}
data:
  .gitconfig: |
    [user]
    name = '{{ .Values.participant.name }}'
    email = "test@foo.com"
