apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.participant.name }}
  namespace: {{ .Values.namespace }}
  annotations:
    # add an annotation indicating the issuer to use.
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  rules:
  - host: {{ .Values.participant.name }}.k8s.aws-tests.skyworkz.nl
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.participant.name }}
            port:
              number: 3000
  tls:
  - hosts:
    - {{ .Values.participant.name }}.k8s.aws-tests.skyworkz.nl
    secretName: {{ .Values.participant.name }}-tls
