apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.participant.name }}
  namespace: participant-{{ .Values.participant.name }}
  annotations:
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-write-timeout: "3600"
    # nginx.ingress.kubernetes.io/auth-url: "https://oauth2.k8s.aws-tests.skyworkz.nl/oauth2/auth
    # https://oauth2-proxy.github.io/oauth2-proxy/docs/features/endpoints/
    # nginx.ingress.kubernetes.io/auth-url: "https://oauth2.k8s.aws-tests.skyworkz.nl/oauth2/auth?allowed_emails={{ .Values.participant.email }}{{ include "trainers_comma_separated" $ }}"
    # nginx.ingress.kubernetes.io/auth-signin: "https://oauth2.k8s.aws-tests.skyworkz.nl/oauth2/start?rd=/redirect/$http_host$escaped_request_uri"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    # add an annotation indicating the issuer to use.
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  rules:
  - host: {{ .Values.participant.name }}.k8s.aws-tests.skyworkz.nl
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.participant.name }}
            port:
              number: 3000
  tls:
  - hosts:
    - {{ .Values.participant.name }}.k8s.aws-tests.skyworkz.nl
    secretName: {{ .Values.participant.name }}-tls
