apiVersion: v1
kind: LimitRange
metadata:
  name: mem-limit-range
  namespace: participant-{{ .Values.participant.name }}
spec:
  limits:
  - default:
      memory: 512Mi
    defaultRequest:
      memory: 256Mi
    type: Container
