apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.participant.name }}-project
  namespace: {{ .Release.namespace }}
spec:
  storageClassName: gp2
  accessModes: [ "ReadWriteOnce" ]
  resources:
    requests:
      storage: 10Gi
