apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: participant-{{ .Values.participant.name }}-role-binding
  namespace: participant-{{ .Values.participant.name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: participant-{{ .Values.participant.name }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.participant.name }}
  namespace: participant-{{ .Values.participant.name }}
