apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: participant-{{ .Values.participant.name }}
  namespace: {{ .Release.namespace }}
rules:
- apiGroups: ['*']
  resources: ['*']
  verbs: ['*']
