apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.participant.name }}
  namespace: participant-{{ .Values.participant.name }}
spec:
  selector:
    app: {{ .Values.participant.name }}
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
    name: {{ .Values.participant.name }}
