apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
spec:
  template:
    spec:
      containers:
      - name: main
        command:
        - minio
        - server
        - /data
        - --console-address
        - ":9001"
        ports:
          - containerPort: 9000
            name: api
          - containerPort: 9001
            name: console

---
apiVersion: v1
kind: Service
metadata:
  name: minio
spec:
  ports:
  - name: api
    port: 9000
    protocol: TCP
    targetPort: 9000
  - name: console
    port: 9001
    protocol: TCP
    targetPort: 9001

