---
apiVersion: v1
kind: Secret
metadata:
  name: participant-workspace
  namespace: participant-{{ .Values.participant.name }}
stringData:
  #git_url: git@github.com:skyworkz/kubernetes-training-setup-aws.git
  git_url: {{ .Values.repository_url }}
  git_ssh_key: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
    QyNTUxOQAAACCY7Y+6x/kZGZ2j5T5ByIAzMFpe41MsTtZZ3Bhhr0TwSAAAAKCiv9UQor/V
    EAAAAAtzc2gtZWQyNTUxOQAAACCY7Y+6x/kZGZ2j5T5ByIAzMFpe41MsTtZZ3Bhhr0TwSA
    AAAECDXeGce4bdAtWFgOSiqc2JYzd1t7dM4UyEvrXNJQCF4Zjtj7rH+RkZnaPlPkHIgDMw
    Wl7jUyxO1lncGGGvRPBIAAAAGWxlb25hcmRvLmxvYmF0b0BnbWFpbC5jb20BAgME
    -----END OPENSSH PRIVATE KEY-----



