apiVersion: v1
kind: Secret
metadata:
  name: ssh-config
  namespace: participant-{{ .Values.participant.name }}
stringData:
  ssh_config: |
    Host github.com
    User git
    Port 22
    IdentitiesOnly yes
    UserKnownHostsFile /dev/null
    StrictHostKeyChecking no
