apiVersion: v1
kind: Secret
metadata:
  name: ssh-config
  namespace: {{ .Values.namespace }}
stringData:
  ssh_config: |
    Host github.com
    User git
    Port 22
    IdentitiesOnly yes
    UserKnownHostsFile /dev/null
    StrictHostKeyChecking no
