apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: leonardo 
namePrefix:  leonardo-

resources:
- ../aws

patches:
- target:
    kind: Ingress
    name: kubetrain
  patch: |-
    - op: replace
      path: /spec/rules/0/host
      value:  leonardo.k8s.aws-tests.skyworkz.nl
    - op: replace
      path: /spec/tls/0/hosts/0
      value:  leonardo.k8s.aws-tests.skyworkz.nl
- target:
    kind: Ingress
    name: kubetrain-oauth2-proxy
  patch: |-
    - op: replace
      path: /spec/rules/0/host
      value:  leonardo.k8s.aws-tests.skyworkz.nl
    - op: replace
      path: /spec/tls/0/hosts/0
      value:  leonardo.k8s.aws-tests.skyworkz.nl
