apiVersion: v1
kind: Secret
metadata:
  name: github-client-secret
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app.kubernetes.io/part-of: argocd
type: Opaque
data:
  client-id: SXYxLjAyMjMyYzk0MGI4ZjdlMTM=
  client-secret: NTIyMzgxNTVkZjRmYjk1NzczNDQ4MmI2YzIxZjdlOTlhZDczOGZjYQ==
  cookie-secret: dWZ6eDcwZkV6ZVRZbUREbHlQUUFwbE9yVVBydDdnS1BjX3Z5R2hpUXlrMD0=
