apiVersion: v1
kind: Secret
metadata:
  name: github-client-secret
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app.kubernetes.io/part-of: argocd
type: Opaque
data:
  dex.github.clientSecret: NTIyMzgxNTVkZjRmYjk1NzczNDQ4MmI2YzIxZjdlOTlhZDczOGZjYQ==