apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argo-workflows

resources:
- ../../base
- webhook-router-ingress.yaml
- argo-server-ingress.yaml
- secret-argo-workflows-sso.yaml
- minio-ingress.yaml

patchesStrategicMerge:
- argo-server.yaml
- workflow-controller-configmap.yaml

