apiVersion: v1
kind: ConfigMap
metadata:
  name: workflow-controller-configmap
data:
  artifactRepository: |
    archiveLogs: true
    s3:
      bucket: my-bucket
      endpoint: minio:9000
      insecure: true
      accessKeySecret:
        name: my-minio-cred
        key: accesskey
      secretKeySecret:
        name: my-minio-cred
        key: secretkey
  workflowDefaults: |
    metadata:
      labels:
        workload-type: argo-workflow
    spec:
      # Workflows must complete within 1800secs (30min)
      activeDeadlineSeconds: 1800
      # Remove successful workflows after 3600secs (1hr),
      # Remove failed workflows after 14400secs (4hrs)
      ttlStrategy:
        secondsAfterSuccess: 3600
        secondsAfterFailure: 14400
  sso: |
    # This is the root URL of the OIDC provider (required).
    issuer: https://argocd.k8s-training.aws-tests.skyworkz.nl/api/dex
    # This is name of the secret and the key in it that contain OIDC client
    # ID issued to the application by the provider (required).
    clientId:
      name: argo-workflows-sso
      key: client-id
    # This is name of the secret and the key in it that contain OIDC client
    # secret issued to the application by the provider (required).
    clientSecret:
      name: argo-workflows-sso
      key: client-secret
    # This is the redirect URL supplied to the provider (required). It must
    # be in the form <argo-server-root-url>/oauth2/callback. It must be
    # browser-accessible.
    redirectUrl: https://argo.k8s-training.aws-tests.skyworkz.nl/oauth2/callback

