apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: sealed-secrets-controller
  namespace: kube-system
spec:
  repo: https://bitnami-labs.github.io/sealed-secrets
  chart: sealed-secrets
  version: 2.1.5
  targetNamespace: kube-system
  valuesContent: |-
    image:
      registry: docker.io
    updateStatus: true
    keyrenewperiod: 0
